# This file is used only to track tracer dependencies. It's not meant to be used
# by end users so no integrations dependencies must be added here. If you update
# or add a new dependency, remember to commit the `vendor` folder.

# ignore integrations dependencies
ignored = [
  "github.com/cihub/seelog",
  "github.com/garyburd/*",
  "github.com/gin-gonic/gin",
  "github.com/go-martini/*",
  "github.com/go-redis/redis",
  "github.com/go-sql-driver/mysql",
  "github.com/gocql/gocql",
  "github.com/golang/*",
  "github.com/gorilla/mux",
  "github.com/jmoiron/sqlx",
  "github.com/julienschmidt/*",
  "github.com/lib/pq",
  "github.com/opentracing/*",
  "github.com/stretchr/*",
  "golang.org/x/*",
  "google.golang.org/*",
  "google.golang.org/grpc",
  "gopkg.in/olivere/elastic.v3",
  "gopkg.in/olivere/elastic.v5",
]

[[constraint]]
  name = "github.com/ugorji/go"
  revision = "9c7f9b7a2bc3a520f7c7b30b34b7f85f47fe27b6"
